spring:
  application.name: mvc
  datasource:
    url: jdbc:mysql://localhost:3306/customer_registry
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update  # ← MUDE DE 'none' PARA 'update'
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
logging:
  level:
    org.flywaydb: DEBUG


#  Spring Error Handling
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

# Telemetry
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - prometheus

  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true

#---
#spring:
#  profile.active: local
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ""
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


